### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by WSrujan** [GatoLoko/novel2epub#1]
how to download multiple volume at once?

**Comment by GatoLoko** [comment]
Novel2Epub does not provide such functionality, and depending on the
source, the servers could refuse to support multiple simultaneous
conections, so I don't have plans to support it.

That said, it's easy to download them sequentially with a single command.
Here is a sample using bash shell to download volumes 1 through 5 of mga:

for i in `seq 1 5`; do novel2epub mga $i; done
